### ISSUE TITLE
96Boards Media Sever

### ISSUE THREAD

**Issue by ric96** [96boards-projects/staging#2]
This project is a set of instructions to make any 96Boards CE running Debian Linux into a Media Server.

This project utilizes the miniDLNA and UPNP(Universal Plug and Play) protocols to make steaming multimedia content from a 96Boards CE device to any Smart Phone/TV or Computer connected to your local network a breeze.

**Comment by Mani-Sadhasivam** [comment]
Sounds good! Please go ahead.

This issue will be closed once the project has been accepted.

Thanks!

**Comment by Mani-Sadhasivam** [comment]
Closing the issue as the project successfully made it way into Projects Org.

Thanks @ric96!
